name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
      
    - name: Build with Maven
      run: mvn -B -e verify
    
    
    - name: "telegram Notify"
      uses: "appleboy/telegram-action@master"
      with: 
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: New version publish
